modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPLv3.0"

issueTrackerURL = "https://github.com/62832/PolymorphicEnergistics/issues"
displayURL = "https://github.com/62832/PolymorphicEnergistics"

[[mods]]
    modId = "polyeng"
    version = "$version"
    displayName = "Polymorphic Energistics"
    logoFile = "icon.png"
    authors = "90"
    description = "Polymorph support for Applied Energistics 2."

[[dependencies.polyeng]]
    modId = "ae2"
    mandatory = true
    versionRange = "[$ae2Version,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.polyeng]]
    modId = "polymorph"
    mandatory = true
    versionRange = "[$polymorphVersion,)"
    ordering = "AFTER"
    side = "BOTH"
