modLoader = "javafml"
loaderVersion = "[1,)"

issueTrackerURL = "https://github.com/62832/PolymorphicEnergistics/issues"
displayURL = "https://github.com/62832/PolymorphicEnergistics"
logoFile = "icon.png"
authors = "90"
license = "LGPLv3.0"

[[mods]]
modId = "polyeng"
version = "$version"
displayName = "Polymorphic Energistics"
description = "Polymorph support for Applied Energistics 2."

[[mixins]]
config = "polyeng.mixins.json"

[[dependencies]]
modId = "minecraft"
versionRange = "[$mcVersion,)"

[[dependencies]]
modId = "ae2"
versionRange = "[$ae2Version,)"

[[dependencies]]
modId = "polymorph"
versionRange = "[$polymorphVersion,)"
