name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build release files
        id: build
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: ./gradlew build
      - name: Publish release files
        uses: Kir-Antipov/mc-publish@c0f30ad683340ba9a5374ba42157179f30171107
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          curseforge-id: 941096
          curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}

          modrinth-id: VS1a14jA
          modrinth-token: ${{ secrets.MODRINTH_API_KEY }}

          game-versions: 1.20.4
          loaders: neoforge
          dependencies: |
            ae2(required){curseforge:223794}{modrinth:XxWD5pD3}
            polymorph(required){curseforge:388800}{modrinth:tagwiZkJ}
